Crypto Pay API
Crypto Pay is a payment system based on Crypto Bot that allows you to accept payments in crypto and transfer coins to users using our API.
Subscribe to our News Channel to be the first to know about the latest updates and join the discussion in our chat.
Recent changes
Crypto Pay API 1.4 (21 June, 2024)
Added the fields mini_app_invoice_url, web_app_invoice_url to the class Invoice
Crypto Pay API 1.3 (15 March, 2024)
Added the ability to get app statistics using the getStats method and the class AppStats.
Added the ability to create checks with attachment to the user through the id or his username.
Crypto Pay API 1.2 (24 November, 2023)
Added the methods createCheck, deleteCheck, getChecks and the class Check to manage checks by using the app.
Added the parameters currency_type, fiat and accepted_assets to the method createInvoice to create invoices for the amount specified in a fiat currency.
Added the ability to delete invoices using the method deleteInvoice.
Added the ability to get the list of transfers using the method getTransfers.
Added the fields currency_type, fiat, paid_asset, paid_amount, paid_usd_rate,  paid_fiat_rate, fee_asset, fee_amount and accepted_assets to the class Invoice.
The field fee in the Webhook update payload is now deprecated, use the new field fee_amount in the class Invoice instead.
The field usd_rate in the Webhook update payload is now deprecated, use the new field paid_usd_rate in the class Invoice instead.
The field pay_url is now deprecated, use the new field bot_invoice_url in the class Invoice instead.
Added the field onhold to the class Balance.
Crypto Pay API 1.1.5 (September 30, 2023)
Discontinued support for BUSD.
Crypto Pay API 1.1.4 (September 22, 2023)
Added support for LTC to the mainnet.
Crypto Pay API 1.1.3 (October 3, 2022)
Added the field fee to the class Invoice to show the amount of charged service fees. Returned only in the Webhook update payload.
Added the field usd_rate to the class Invoice to show the price of the asset in USD. Returned only in the Webhook update payload.
Crypto Pay API 1.1.2 (September 5, 2022)
Method transfer is disabled by default for new apps.
You can set an allowlist of IP addresses under the “Security” button in the app settings.
Crypto Pay API 1.1.1 (July 26, 2022)
Added support for ETH to the mainnet.
Crypto Pay API 1.1 (February 2, 2022)
Apps can now send coins to users using the new method transfer.
Added support for hidden message in invoices.
New parameter expires_in to set a payment time limit for new invoices.
Added new expiration_date field in Invoice object.
Note: In order to use the new method transfer, you need to create a new app.
Authorizing your app
First, you need to create a new app and get API token. Open @CryptoBot (@CryptoTestnetBot for testnet), go to Crypto Pay and tap Create App to get API Token.
All queries to Crypto Pay API must be served over HTTPS. Use either URL query string or application/json or application/x-www-form-urlencoded or multipart/form-data for passing parameters. API Token must be passed in the header parameter Crypto-Pay-API-Token. URL must be presented in this form: https://pay.crypt.bot/api/%method%. Example request:
GET /api/getMe HTTP/1.1
Host: pay.crypt.bot
Crypto-Pay-API-Token: 123456789:AAzQcZWQqQAbsfgPnOLr4FHC8Doa4L7KryC
Testnet: 
Bot: @CryptoTestnetBot
URL: https://testnet-pay.crypt.bot/
Mainnet:
Bot: @CryptoBot
URL: https://pay.crypt.bot/
